
	VIEW IN ORACLE
	**************
	
	*	In Oracle, view is a virtual table that does not physically exist. 
		It is stored in Oracle data dictionary and do not store any data. It can be executed when called.

	*	A view is created by a query joining one or more tables.
	
	1. CREATE TABLE
	   ************

		*	CREATE TABLE PRODUCTS(
			PRODUCT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
			SUPPLIER_NAME VARCHAR2(100) NOT NULL,
			PRODUCT_NAME VARCHAR2(100) NOT NULL,
			PRODUCT_PRICE NUMBER NOT NULL);

		*	SELECT * FROM PRODUCTS;
		
--------------------------------------------------------------------------------------------------------------------------------

	2. CREATE VIEW IN THAT TABLE
	   *************************
	
		*	CREATE VIEW ORDER_PRODUCTS
			AS
			SELECT * FROM PRODUCTS
			WHERE PRODUCT_PRICE>15000;

		*	SELECT * FROM ORDER_PRODUCTS;

--------------------------------------------------------------------------------------------------------------------------------

	3.	ORACLE UPDATE VIEW
		******************
		
		*	In Oracle, the CREATE OR REPLACE VIEW statement is used to modify the definition of an Oracle VIEW without dropping it.

		*	CREATE OR REPLACE VIEW ORDER_PRODUCTS AS
			SELECT * FROM PRODUCTS
			WHERE PRODUCT_PRICE>17000;
			
--------------------------------------------------------------------------------------------------------------------------------

	4.	ORACLE DROP VIEW
		****************
		
	*	The DROP VIEW statement is used to remove or delete the VIEW completely.

	*	Syntax:

			DROP VIEW view_name;  
		
	*	Example:

			DROP VIEW ORDER_PRODUCTS;	


