
	STORED PROCEDURE IN ORACLE
	**************************
	
	1.	Create Table In Oracle 
		**********************
		
		*	CREATE TABLE GAMES(
			Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
			Name VARCHAR2(50) NOT NULL,
			Category VARCHAR2(100)  NOT NULL,
			PRIMARY KEY (Id)
			);

		*	SELECT * FROM GAMES;
		
--------------------------------------------------------------------------------------------------------------------------------
		
	2.	INSERT DATA INTO ORACLE
		***********************		

		*	INSERT INTO GAMES (Name, Category) VALUES('PUBG', 'Survival');
			INSERT INTO GAMES (Name, Category) VALUES('Overwatch', 'Shooting');

--------------------------------------------------------------------------------------------------------------------------------

	3.	CREATE STORED PROCEDURE
		***********************
		
		*	CREATE OR REPLACE PROCEDURE GETGAMESBYCATEGORY (
			GameId Number )
			IS
			gameDetails GAMES%ROWTYPE;
			BEGIN 
				SELECT * 
				INTO gameDetails
				FROM GAMES
				WHERE Id = GameId;
			END;
			
--------------------------------------------------------------------------------------------------------------------------------

	4.	EXECUTE THE STORED PROCEDURE
		****************************

		EXEC GETGAMESBYCATEGORY(2);

--------------------------------------------------------------------------------------------------------------------------------

	5. SAME THING IN VARCHAR (STORED PROCEDURE)
	   ****************************************

		CREATE OR REPLACE PROCEDURE GETGAMESBYCATEGORY (
		GameCategory VARCHAR2)
		IS
		gameDetails GAMES%ROWTYPE;
		BEGIN 
			SELECT * 
			INTO gameDetails
			FROM GAMES
			WHERE Category = GameCategory;
  
			dbms_output.put_line(gameDetails.Name);
		END;    

--------------------------------------------------------------------------------------------------------------------------------

	6.	EXECUTE THE STORED PROCEDURE DATA
		*********************************
		
		SET serveroutput ON;
		
		EXEC GETGAMESBYCATEGORY('Shooting');

--------------------------------------------------------------------------------------------------------------------------------
